[package]
name = "aoc22"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.13"
regex = "1.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

